! This automatically generated Fortran wrapper file allows codes
! written in Fortran to be called directly from C and translates all
! C-style arguments into expected Fortran-style arguments (with
! assumed size, local type declarations, etc.).


SUBROUTINE C_FOO() BIND(C)
  IMPLICIT NONE

  INTERFACE
    SUBROUTINE FOO()
      IMPLICIT NONE
    END SUBROUTINE FOO
  END INTERFACE

  CALL FOO()
END SUBROUTINE C_FOO


SUBROUTINE C_GENERATECOMPLETEBINARYTREENEW(HEIGHT, TREERESULT_DIM_1, TREERESULT_DIM_2, TREERESULT) BIND(C)
  USE ISO_C_BINDING, ONLY: C_BOOL
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: HEIGHT
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TREERESULT_DIM_1
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TREERESULT_DIM_2
  INTEGER :: TREERESULT_COPY_COUNTER
  CHARACTER(LEN=TREERESULT_DIM_1) :: TREERESULT_STRING
  CHARACTER, DIMENSION(TREERESULT_DIM_1,TREERESULT_DIM_2) :: TREERESULT

  INTERFACE
    FUNCTION GENERATECOMPLETEBINARYTREENEW(HEIGHT) RESULT(TREERESULT)
      !  This function returns the words representing a complete binary tree, producing the labels of its leaves
      !  (which are words composed of the letters {{0, 1}}). The height of the tree must be at least 1.
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: HEIGHT
      CHARACTER(LEN=20), DIMENSION(20,2**HEIGHT) :: TREERESULT
    END FUNCTION GENERATECOMPLETEBINARYTREENEW
  END INTERFACE

  TREERESULT_STRING = GENERATECOMPLETEBINARYTREENEW(HEIGHT)
  
  DO TREERESULT_COPY_COUNTER = 1, SIZE(TREERESULT,1)
    TREERESULT(TREERESULT_COPY_COUNTER) = TREERESULT_STRING(TREERESULT_COPY_COUNTER:TREERESULT_COPY_COUNTER)
  END DO
END SUBROUTINE C_GENERATECOMPLETEBINARYTREENEW

